/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function playSystemSound(soundName: SystemSoundName): void

export declare function plus100(input: number): number

export declare const enum SystemSoundName {
  Tink = 0,
  Pop = 1,
  Glass = 2,
  Hero = 3,
  Morse = 4,
  Ping = 5,
  Purr = 6,
  Sosumi = 7,
  Submarine = 8,
  Blow = 9,
  Bottle = 10,
  Frog = 11,
  Funk = 12,
  Basso = 13
}
